[server]
host-name=printserver
domain-name=local
use-ipv4=yes
use-ipv6=no
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[publish]
publish-hinfo=no
publish-workstation=no
publish-domain=yes

[rlimits]
rlimit-nofile=10000