# =============================================
# Configuracao do Samba - Print Server
# =============================================
[global]
   workgroup = WORKGROUP
   server string = Print Server DEX
   server role = standalone server
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   panic action = /usr/share/samba/panic-action %d

   # Seguranca
   map to guest = Bad User
   dns proxy = No

   # Performance
   socket options = TCP_NODELAY IPTOS_LOWDELAY
   read raw = Yes
   write raw = Yes
   use sendfile = Yes
   aio read size = 16384
   aio write size = 16384

   # Anunciar impressoras do CUPS
   printcap name = cups
   printing = cups
   load printers = Yes

[printers]
   comment = All Printers
   path = /var/spool/samba
   browseable = Yes
   read only = No
   guest ok = Yes
   writable = No
   printable = Yes
   printer admin = root, @lpadmin

[print$]
   comment = Printer Drivers
   path = /var/lib/samba/printers
   browseable = Yes
   read only = No
   guest ok = Yes