#!/bin/bash
# =============================================
# IP fixo do print server
#   ps-ip           -> menu interativo
#   ps-ip --auto    -> fixa o IP atual (usado no instalador)
#   ps-ip --dhcp    -> volta para DHCP do roteador
#   Ethernet -> /etc/network/interfaces (ifupdown)
#   WiFi     -> NetworkManager (nmcli)
# =============================================
set -e

_PS_SCRIPT="$(readlink -f "${BASH_SOURCE[0]}")"
_REPO_DIR="$(dirname "$(dirname "$_PS_SCRIPT")")"
. "$_REPO_DIR/lib/i18n.sh"

MODE="${1:-interactive}"

if [ "$(id -u)" -ne 0 ]; then
    echo "$(t ROOT_ERR)"
    exit 1
fi

ask() { local v; read -e -i "$2" -r -p "$1: " v; echo "${v:-$2}"; }

DEV=$(ip -4 route show default | awk '{print $5; exit}')
if [ -z "$DEV" ]; then
    echo "$(t IP_NOROUTE)"
    exit 1
fi

IPCIDR=$(ip -4 -o addr show dev "$DEV" | awk '$3=="inet"{print $4; exit}')
[ -z "$IPCIDR" ] && { tf IP_NOADDR "$DEV"; exit 1; }
GW=$(ip -4 route show default | awk '{print $3; exit}')
DNS=$(awk '/^nameserver/{printf "%s ",$2}' /etc/resolv.conf)

# Em --auto nao fixa IP de loopback/link-local (sem RHCP valido)
case "$IPCIDR" in
    169.254.*|127.*)
        echo "$(t IP_LINKLOCAL)"
        exit 1 ;;
esac

mask_from_cidr() {
    local pre=$1
    local bits=$(( (1<<32) - (1<<(32-pre)) ))
    echo "$(( (bits>>24)&255 )).$(( (bits>>16)&255 )).$(( (bits>>8)&255 )).$(( bits&255 ))"
}

if [ -d "/sys/class/net/$DEV/phy80211" ]; then
    # ---------------- WiFi (NetworkManager) ----------------
    CON=$(nmcli -t -f NAME,DEVICE con show --active | awk -F: -v d="$DEV" '$2==d{print $1; exit}')
    [ -z "$CON" ] && { echo "$(t IP_NMCONN)"; exit 1; }

    if [ "$MODE" = "--dhcp" ]; then
        nmcli con modify "$CON" ipv4.method auto ipv4.addresses "" ipv4.gateway "" ipv4.dns ""
        nmcli con up "$CON" >/dev/null
        echo "$(t IP_DHCP_OK)"
        exit 0
    fi

    tf IP_WIFIIFACE "$DEV" "$CON"
    tf IP_MAC "$(cat /sys/class/net/$DEV/address)"
    echo ""

    if [ "$MODE" = "--auto" ]; then
        NW_IP=$IPCIDR; GW2=$GW; DNSW=$DNS
    else
        NW_IP=$(ask "$(tf IP_PROMPT_IP "$IPCIDR")" "$IPCIDR")
        GW2=$(ask "$(t IP_PROMPT_GW)" "$GW")
        DNSW=$(ask "$(t IP_PROMPT_DNS)" "${DNS:-8.8.8.8 8.8.4.4}")
    fi

    echo ""
    echo "$(t IP_APPLY_NM)"
    mkdir -p /root/net-backup
    nmcli con show "$CON" > "/root/net-backup/${CON}.$(date +%Y%m%d_%H%M%S)"
    nmcli con modify "$CON" ipv4.method manual ipv4.addresses "$NW_IP" ipv4.gateway "$GW2" ipv4.dns "$DNSW"
    echo "$(t IP_RECONNECT)"
    nmcli con up "$CON"
    echo ""
    tf IP_NEWIP "$NW_IP"
    echo "$(t IP_HINT)"
else
    # ---------------- Ethernet (ifupdown) ----------------
    tf IP_ETHIFACE "$DEV"

    if [ "$MODE" = "--dhcp" ]; then
        mkdir -p /root/net-backup
        cp /etc/network/interfaces "/root/net-backup/interfaces.$(date +%Y%m%d_%H%M%S)" 2>/dev/null || true
        cat > /etc/network/interfaces <<EOF
# Generated by ps-ip --dhcp (backup in /root/net-backup)
auto lo
iface lo inet loopback

auto $DEV
iface $DEV inet dhcp
EOF
        echo "$(t IP_DHCP_OK)"
        echo "$(t IP_REBOOT_HINT)"
        exit 0
    fi

    if [ "$MODE" = "--auto" ]; then
        NW_IP=$IPCIDR; GW2=$GW
        MASKN=$(mask_from_cidr "${IPCIDR#*/}")
        DNSW=$DNS
    else
        NW_IP=$(ask "$(tf IP_PROMPT_IP "$IPCIDR")" "$IPCIDR")
        GW2=$(ask "$(t IP_PROMPT_GW)" "$GW")
        MASKN=$(ask "$(t IP_PROMPT_MASK)" "$(mask_from_cidr "${IPCIDR#*/}")")
        DNSW=$(ask "$(t IP_PROMPT_DNS)" "${DNS:-8.8.8.8 8.8.4.4}")
    fi

    echo ""
    echo "$(t IP_WRITE)"
    mkdir -p /root/net-backup
    cp /etc/network/interfaces "/root/net-backup/interfaces.$(date +%Y%m%d_%H%M%S)" 2>/dev/null || true
    cat > /etc/network/interfaces <<EOF
# Generated by ps-ip (backup in /root/net-backup)
auto lo
iface lo inet loopback

auto $DEV
iface $DEV inet static
    address $NW_IP
    netmask $MASKN
    gateway $GW2
    dns-nameservers $DNSW
EOF

    cp /etc/resolv.conf "/root/net-backup/resolv.conf.$(date +%Y%m%d_%H%M%S)" 2>/dev/null || true
    printf '%s\n' $DNSW | sed 's/^/nameserver /' > /etc/resolv.conf

    echo "$(t IP_APPLY_HOT)"
    ip addr replace "$NW_IP" dev "$DEV" || true
    ip route replace default via "$GW2" || true

    echo ""
    tf IP_NEWIP "$NW_IP"
    echo "$(t IP_REBOOT_HINT)"
fi